db:
  url: mongo://admin:admin@localhost:27017 # DB_URL environment variable
  auth: true # DB_AUTH environment variable
  max_connections: 20 # DB_MAX_CONNECTIONS environment variable
  min_pool_size: 1 # DB_MIN_POOL_SIZE environment variable

auth:
  jwt_secret: my_secret # JWT_SECRET environment variable
  jwt_expires_in: 60m # JWT_EXPIRES_IN environment variable
  jwt_refresh_secret: my_secret # JWT_REFRESH_SECRET environment variable
  jwt_refresh_expires_in: 24h # JWT_REFRESH_EXPIRES_IN environment variable
